version: "3"
services:

  hono-drizzle-app:
    build:
      dockerfile: Dockerfile
      context: ./
    container_name: hono-drizzle-app
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - .:/app
      - /app/node_modules

    env_file:
      - .env
  